
title: My Resume
url: 'http://chenhuijie.com'
baseurl: 'Resume/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: 陈辉杰
tagline: 资产管理、风控专员
pic: profile3.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: chenhuijie23@icloud.com
phone: 13556083055
website: www.chenhuijie.com #do not add http://
linkedin: chenhuijie23
github: chenhuijie23
twitter: '@JetChan31'

#Update all the sections by editing the files inside _includes folder.
